# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(default='Oops'),
            preserve_default=False,
        ),
    ]
